server:
  port: 8080

spring:
  application:
    name: badwallet-api
  datasource:
    url: jdbc:postgresql://localhost:5432/badwalletdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
